/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.project.formularios;

import com.project.configuraciones.MisVariables;
import com.project.daos.AccesosDAO;
import com.project.daos.UsuariosDAO;
import com.project.dominios.misConstantes;
import com.project.modelos.Acceso;
import com.project.modelos.Usuarios;
import com.project.utilidades.Seguridad;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author santi
 */
public final class Login extends javax.swing.JFrame {

    int count, count2, count3;
    public String documentoUsuarioC, nombresUsuarioC, apellidosUsuarioC, fechaTextoC;

    private int posicionX;
    private int posicionY;

    private final String textoCorreo = "Correo electronico";
    private final String contraseña = "Contraseña";
    private final String textoDocumento = "No Documento";
    private final String textoNombres = "Nombres";
    private final String textoApellidos = "Apellidos";

    private final Pattern correoValido = Pattern.compile("^[a-zA-Z0-9_!#$%&’*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$");

    Action activarTeclado = new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent evento) {
            cajitaContrasena.requestFocus();
            VerificarCajaContrasena(cajitaCorreo, cajitaContrasena);
        }
    };
    Action activarTeclado2 = new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent evento) {
            panelIniciarSesion.requestFocus();
            AceptarPanel2(cajitaCorreo, cajitaContrasena, panelPrincipal);
        }
    };

    Action activarTeclado3 = new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent evento) {
            cajitaContrasena2.requestFocus();
            VerificarCajaContrasena(cajitaCorreo2, cajitaContrasena2);
        }
    };
    Action activarTeclado4 = new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent evento) {

            AceptarPanel(cajitaCorreo2, cajitaContrasena2, panelRegistrar2);
        }
    };
    Action activarTeclado5 = new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent evento) {

            cajitaNombres.requestFocus();
        }
    };
    Action activarTeclado6 = new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent evento) {

            cajitaApellidos.requestFocus();
        }
    };
    Action activarTeclado7 = new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent evento) {

            cajitaFecha.requestFocusInWindow();
        }
    };

    public Login() {
        initComponents();

        inicioAbrir();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelCabecera = new javax.swing.JPanel();
        panelMinimizar = new javax.swing.JPanel();
        lblMinimizar1 = new javax.swing.JLabel();
        lblMinimizar1_2 = new javax.swing.JLabel();
        panelCerrar = new javax.swing.JPanel();
        lblCerrar1 = new javax.swing.JLabel();
        lblCerrar1_2 = new javax.swing.JLabel();
        panelLogo = new javax.swing.JPanel();
        iconLogo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        panelIconLogin = new javax.swing.JPanel();
        iconUser = new javax.swing.JLabel();
        cajitaCorreo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        panelIconPassword = new javax.swing.JPanel();
        iconPassword = new javax.swing.JLabel();
        verContrasena = new javax.swing.JPanel();
        ojoNoOculto = new javax.swing.JLabel();
        ojoOculto = new javax.swing.JLabel();
        cajitaContrasena = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        panelIniciarSesion = new javax.swing.JPanel();
        lblIniciarSesion = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        panelRegistrar = new javax.swing.JPanel();
        lblRegistrar = new javax.swing.JLabel();
        separadorCrear = new javax.swing.JSeparator();
        Fondo = new javax.swing.JLabel();
        panelRegistrar1 = new javax.swing.JPanel();
        PanelCabecera2 = new javax.swing.JPanel();
        panelLogo2 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        panelMinimizar2 = new javax.swing.JPanel();
        lblMinimizar2 = new javax.swing.JLabel();
        lblMinimizar2_2 = new javax.swing.JLabel();
        panelCerrar2 = new javax.swing.JPanel();
        lblCerrar2 = new javax.swing.JLabel();
        lblCerrar2_2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cajitaDocumento = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cajitaNombres = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cajitaApellidos = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cajitaFecha = new com.toedter.calendar.JDateChooser();
        panelAtras = new javax.swing.JPanel();
        lblAtras = new javax.swing.JLabel();
        panelSiguiente = new javax.swing.JPanel();
        lblSiguiente = new javax.swing.JLabel();
        Fondo2 = new javax.swing.JLabel();
        panelRegistrar2 = new javax.swing.JPanel();
        panelCabcera3 = new javax.swing.JPanel();
        panelLogo3 = new javax.swing.JPanel();
        lblLogo3 = new javax.swing.JLabel();
        lblTitulo3 = new javax.swing.JLabel();
        panelMinimizar3 = new javax.swing.JPanel();
        lblMinimizar3 = new javax.swing.JLabel();
        lblMinimizar3_2 = new javax.swing.JLabel();
        panelCerrar3 = new javax.swing.JPanel();
        lblcerrar3 = new javax.swing.JLabel();
        lblcerrar3_2 = new javax.swing.JLabel();
        panelIconRegistro = new javax.swing.JPanel();
        lblIconRegistro = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cajitaCorreo2 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        verContrasena2 = new javax.swing.JPanel();
        ojoNoOculto1 = new javax.swing.JLabel();
        ojoOculto1 = new javax.swing.JLabel();
        cajitaContrasena2 = new javax.swing.JPasswordField();
        jSeparator8 = new javax.swing.JSeparator();
        panelAtras2 = new javax.swing.JPanel();
        lblAtras2 = new javax.swing.JLabel();
        panelRegistrarse2 = new javax.swing.JPanel();
        lblRegistrarse2 = new javax.swing.JLabel();
        lblRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PASSME");
        setAlwaysOnTop(true);
        setIconImages(getIconImages());
        setUndecorated(true);
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setOpaque(false);
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCabecera.setBackground(new java.awt.Color(172, 138, 24));
        panelCabecera.setMinimumSize(new java.awt.Dimension(870, 50));
        panelCabecera.setPreferredSize(new java.awt.Dimension(870, 50));
        panelCabecera.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelCabeceraMouseDragged(evt);
            }
        });
        panelCabecera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelCabeceraMousePressed(evt);
            }
        });
        panelCabecera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMinimizar.setBackground(new java.awt.Color(172, 138, 24));
        panelMinimizar.setMinimumSize(new java.awt.Dimension(50, 25));
        panelMinimizar.setPreferredSize(new java.awt.Dimension(50, 25));
        panelMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelMinimizarMouseExited(evt);
            }
        });
        panelMinimizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMinimizar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/menos.png"))); // NOI18N
        panelMinimizar.add(lblMinimizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 49));

        lblMinimizar1_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimizar1_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/menos2.png"))); // NOI18N
        panelMinimizar.add(lblMinimizar1_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 49));

        panelCabecera.add(panelMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 60, 49));

        panelCerrar.setBackground(new java.awt.Color(172, 138, 24));
        panelCerrar.setMinimumSize(new java.awt.Dimension(50, 50));
        panelCerrar.setPreferredSize(new java.awt.Dimension(50, 50));
        panelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelCerrarMouseExited(evt);
            }
        });
        panelCerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCerrar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/cerrar2.png"))); // NOI18N
        panelCerrar.add(lblCerrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 49));

        lblCerrar1_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrar1_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/cerrar.png"))); // NOI18N
        panelCerrar.add(lblCerrar1_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 49));

        panelCabecera.add(panelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 60, 49));
        panelCerrar.getAccessibleContext().setAccessibleName("");

        panelLogo.setBackground(new java.awt.Color(172, 138, 24));
        panelLogo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                panelLogoFocusGained(evt);
            }
        });
        panelLogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/logoChiqui.png"))); // NOI18N
        panelLogo.add(iconLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        panelCabecera.add(panelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 49));

        lblTitulo.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("MEPASS");
        panelCabecera.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        panelPrincipal.add(panelCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 50));

        iconUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/user.png"))); // NOI18N

        javax.swing.GroupLayout panelIconLoginLayout = new javax.swing.GroupLayout(panelIconLogin);
        panelIconLogin.setLayout(panelIconLoginLayout);
        panelIconLoginLayout.setHorizontalGroup(
            panelIconLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconUser, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );
        panelIconLoginLayout.setVerticalGroup(
            panelIconLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconUser, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelIconLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        cajitaCorreo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cajitaCorreo.setForeground(new java.awt.Color(255, 255, 255));
        cajitaCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajitaCorreo.setBorder(null);
        cajitaCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cajitaCorreoFocusGained(evt);
            }
        });
        cajitaCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajitaCorreoMousePressed(evt);
            }
        });
        panelPrincipal.add(cajitaCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 580, 40));
        cajitaCorreo.getAccessibleContext().setAccessibleName("");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        panelPrincipal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 580, 10));

        panelIconPassword.setPreferredSize(new java.awt.Dimension(37, 30));

        iconPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/password.png"))); // NOI18N

        javax.swing.GroupLayout panelIconPasswordLayout = new javax.swing.GroupLayout(panelIconPassword);
        panelIconPassword.setLayout(panelIconPasswordLayout);
        panelIconPasswordLayout.setHorizontalGroup(
            panelIconPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );
        panelIconPasswordLayout.setVerticalGroup(
            panelIconPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIconPasswordLayout.createSequentialGroup()
                .addComponent(iconPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelIconPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 35, 35));

        verContrasena.setOpaque(false);
        verContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verContrasenaMouseClicked(evt);
            }
        });

        ojoNoOculto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ojoNoOculto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/atention.png"))); // NOI18N

        ojoOculto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ojoOculto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/hide.png"))); // NOI18N

        javax.swing.GroupLayout verContrasenaLayout = new javax.swing.GroupLayout(verContrasena);
        verContrasena.setLayout(verContrasenaLayout);
        verContrasenaLayout.setHorizontalGroup(
            verContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ojoOculto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ojoNoOculto, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        verContrasenaLayout.setVerticalGroup(
            verContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ojoOculto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ojoNoOculto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelPrincipal.add(verContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 374, 30, 30));

        cajitaContrasena.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cajitaContrasena.setForeground(new java.awt.Color(255, 255, 255));
        cajitaContrasena.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajitaContrasena.setBorder(null);
        cajitaContrasena.setEchoChar('\u25cf');
        cajitaContrasena.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cajitaContrasenaFocusGained(evt);
            }
        });
        cajitaContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajitaContrasenaMousePressed(evt);
            }
        });
        panelPrincipal.add(cajitaContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 580, 40));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        panelPrincipal.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 580, 20));

        panelIniciarSesion.setBackground(new java.awt.Color(255, 102, 255));
        panelIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelIniciarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelIniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelIniciarSesionMouseExited(evt);
            }
        });

        lblIniciarSesion.setBackground(new java.awt.Color(255, 153, 0));
        lblIniciarSesion.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        lblIniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIniciarSesion.setText("Iniciar Sesión");
        lblIniciarSesion.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 153, 0), new java.awt.Color(153, 153, 255)));

        javax.swing.GroupLayout panelIniciarSesionLayout = new javax.swing.GroupLayout(panelIniciarSesion);
        panelIniciarSesion.setLayout(panelIniciarSesionLayout);
        panelIniciarSesionLayout.setHorizontalGroup(
            panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIniciarSesionLayout.createSequentialGroup()
                .addComponent(lblIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelIniciarSesionLayout.setVerticalGroup(
            panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, -1, 30));

        jLabel14.setBackground(new java.awt.Color(255, 153, 102));
        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 153, 0));
        jLabel14.setText("¿Aun no tienes tú cuenta?");
        panelPrincipal.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, -1, -1));

        panelRegistrar.setBackground(new java.awt.Color(255, 204, 51));
        panelRegistrar.setOpaque(false);
        panelRegistrar.setPreferredSize(new java.awt.Dimension(110, 40));
        panelRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelRegistrarMouseExited(evt);
            }
        });

        lblRegistrar.setBackground(new java.awt.Color(204, 204, 204));
        lblRegistrar.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblRegistrar.setForeground(new java.awt.Color(153, 0, 153));
        lblRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistrar.setText("Crea tú cuenta ahora mismo");

        javax.swing.GroupLayout panelRegistrarLayout = new javax.swing.GroupLayout(panelRegistrar);
        panelRegistrar.setLayout(panelRegistrarLayout);
        panelRegistrarLayout.setHorizontalGroup(
            panelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        panelRegistrarLayout.setVerticalGroup(
            panelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrarLayout.createSequentialGroup()
                .addComponent(lblRegistrar)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 520, 170, 20));

        separadorCrear.setBackground(new java.awt.Color(153, 0, 153));
        separadorCrear.setForeground(new java.awt.Color(153, 0, 153));
        separadorCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelPrincipal.add(separadorCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 535, 170, 10));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/loginInterfaz.png"))); // NOI18N
        Fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(172, 138, 24)));
        panelPrincipal.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 580));

        panelRegistrar1.setBackground(new java.awt.Color(0, 0, 0));
        panelRegistrar1.setMinimumSize(new java.awt.Dimension(870, 580));
        panelRegistrar1.setPreferredSize(new java.awt.Dimension(870, 580));
        panelRegistrar1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelCabecera2.setBackground(new java.awt.Color(172, 138, 24));
        PanelCabecera2.setPreferredSize(new java.awt.Dimension(600, 34));
        PanelCabecera2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PanelCabecera2MouseDragged(evt);
            }
        });
        PanelCabecera2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelCabecera2MousePressed(evt);
            }
        });
        PanelCabecera2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLogo2.setBackground(new java.awt.Color(172, 138, 24));
        panelLogo2.setPreferredSize(new java.awt.Dimension(60, 50));
        panelLogo2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                panelLogo2FocusGained(evt);
            }
        });
        panelLogo2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/logoChiqui.png"))); // NOI18N
        panelLogo2.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        PanelCabecera2.add(panelLogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblTitulo2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo2.setText("MEPASS");
        lblTitulo2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblTitulo2FocusGained(evt);
            }
        });
        PanelCabecera2.add(lblTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        panelMinimizar2.setBackground(new java.awt.Color(172, 138, 24));
        panelMinimizar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMinimizar2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelMinimizar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelMinimizar2MouseExited(evt);
            }
        });
        panelMinimizar2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMinimizar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimizar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/menos.png"))); // NOI18N
        panelMinimizar2.add(lblMinimizar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        lblMinimizar2_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimizar2_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/menos2.png"))); // NOI18N
        panelMinimizar2.add(lblMinimizar2_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        PanelCabecera2.add(panelMinimizar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 60, 50));

        panelCerrar2.setBackground(new java.awt.Color(172, 138, 24));
        panelCerrar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCerrar2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelCerrar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelCerrar2MouseExited(evt);
            }
        });
        panelCerrar2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCerrar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/cerrar2.png"))); // NOI18N
        panelCerrar2.add(lblCerrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        lblCerrar2_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrar2_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/cerrar.png"))); // NOI18N
        panelCerrar2.add(lblCerrar2_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        PanelCabecera2.add(panelCerrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 60, 50));

        panelRegistrar1.add(PanelCabecera2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 50));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("* Campo requerido");
        panelRegistrar1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("*");
        panelRegistrar1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 30, 40));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Documento de identidad");
        panelRegistrar1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 340, 30));

        cajitaDocumento.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cajitaDocumento.setForeground(new java.awt.Color(255, 255, 255));
        cajitaDocumento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajitaDocumento.setBorder(null);
        cajitaDocumento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cajitaDocumentoFocusGained(evt);
            }
        });
        cajitaDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajitaDocumentoMousePressed(evt);
            }
        });
        panelRegistrar1.add(cajitaDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 340, 40));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        panelRegistrar1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 340, 10));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("*");
        panelRegistrar1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 30, 30));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombre");
        panelRegistrar1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 340, 30));

        cajitaNombres.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cajitaNombres.setForeground(new java.awt.Color(255, 255, 255));
        cajitaNombres.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajitaNombres.setBorder(null);
        cajitaNombres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cajitaNombresFocusGained(evt);
            }
        });
        cajitaNombres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajitaNombresMousePressed(evt);
            }
        });
        panelRegistrar1.add(cajitaNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 340, 40));

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        panelRegistrar1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 340, 10));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("*");
        panelRegistrar1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 30, 40));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellidos");
        panelRegistrar1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 340, 30));

        cajitaApellidos.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cajitaApellidos.setForeground(new java.awt.Color(255, 255, 255));
        cajitaApellidos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajitaApellidos.setBorder(null);
        cajitaApellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cajitaApellidosFocusGained(evt);
            }
        });
        cajitaApellidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajitaApellidosMousePressed(evt);
            }
        });
        panelRegistrar1.add(cajitaApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 340, 40));

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        panelRegistrar1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 340, 10));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("*");
        panelRegistrar1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 40, 30));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha de nacimiento");
        panelRegistrar1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 340, 30));

        cajitaFecha.setBackground(new java.awt.Color(255, 255, 255));
        cajitaFecha.setForeground(new java.awt.Color(51, 51, 51));
        cajitaFecha.setDateFormatString("y/MM/d");
        cajitaFecha.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cajitaFecha.setOpaque(false);
        panelRegistrar1.add(cajitaFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 390, 40));

        panelAtras.setBackground(new java.awt.Color(255, 102, 102));
        panelAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelAtrasMouseExited(evt);
            }
        });
        panelAtras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAtras.setBackground(new java.awt.Color(255, 102, 102));
        lblAtras.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblAtras.setForeground(new java.awt.Color(255, 255, 255));
        lblAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAtras.setText("Atras");
        lblAtras.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 0), new java.awt.Color(153, 153, 255)));
        panelAtras.add(lblAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        panelRegistrar1.add(panelAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 110, 30));

        panelSiguiente.setBackground(new java.awt.Color(255, 204, 51));
        panelSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSiguienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelSiguienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelSiguienteMouseExited(evt);
            }
        });

        lblSiguiente.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        lblSiguiente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSiguiente.setText("Siguiente");
        lblSiguiente.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 0), new java.awt.Color(153, 153, 255)));

        javax.swing.GroupLayout panelSiguienteLayout = new javax.swing.GroupLayout(panelSiguiente);
        panelSiguiente.setLayout(panelSiguienteLayout);
        panelSiguienteLayout.setHorizontalGroup(
            panelSiguienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        panelSiguienteLayout.setVerticalGroup(
            panelSiguienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelRegistrar1.add(panelSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, 110, 30));

        Fondo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/registroInterfaz.png"))); // NOI18N
        Fondo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(172, 138, 24)));
        Fondo2.setPreferredSize(new java.awt.Dimension(870, 580));
        panelRegistrar1.add(Fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 580));

        panelRegistrar2.setBackground(new java.awt.Color(255, 102, 102));
        panelRegistrar2.setMinimumSize(new java.awt.Dimension(870, 580));
        panelRegistrar2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCabcera3.setBackground(new java.awt.Color(172, 138, 24));
        panelCabcera3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelCabcera3MouseDragged(evt);
            }
        });
        panelCabcera3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelCabcera3MousePressed(evt);
            }
        });
        panelCabcera3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLogo3.setBackground(new java.awt.Color(172, 138, 24));
        panelLogo3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/logoChiqui.png"))); // NOI18N
        panelLogo3.add(lblLogo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        panelCabcera3.add(panelLogo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        lblTitulo3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblTitulo3.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitulo3.setText("MEPASS");
        panelCabcera3.add(lblTitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 50, -1));

        panelMinimizar3.setBackground(new java.awt.Color(172, 138, 24));
        panelMinimizar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMinimizar3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelMinimizar3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelMinimizar3MouseExited(evt);
            }
        });
        panelMinimizar3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMinimizar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimizar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/menos.png"))); // NOI18N
        panelMinimizar3.add(lblMinimizar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        lblMinimizar3_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimizar3_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/menos2.png"))); // NOI18N
        panelMinimizar3.add(lblMinimizar3_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        panelCabcera3.add(panelMinimizar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 60, 50));

        panelCerrar3.setBackground(new java.awt.Color(172, 138, 24));
        panelCerrar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCerrar3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelCerrar3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelCerrar3MouseExited(evt);
            }
        });
        panelCerrar3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblcerrar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcerrar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/cerrar2.png"))); // NOI18N
        panelCerrar3.add(lblcerrar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        lblcerrar3_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcerrar3_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/cerrar.png"))); // NOI18N
        panelCerrar3.add(lblcerrar3_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        panelCabcera3.add(panelCerrar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 60, 50));

        panelRegistrar2.add(panelCabcera3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 50));

        panelIconRegistro.setBackground(new java.awt.Color(255, 255, 255));
        panelIconRegistro.setRequestFocusEnabled(false);
        panelIconRegistro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                panelIconRegistroFocusGained(evt);
            }
        });
        panelIconRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/registro.png"))); // NOI18N
        panelIconRegistro.add(lblIconRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 70));

        panelRegistrar2.add(panelIconRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 70, 70));

        jLabel12.setBackground(new java.awt.Color(255, 102, 102));
        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 102));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("*");
        panelRegistrar2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 310, 30, 30));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Correo electronico");
        panelRegistrar2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 580, 30));

        cajitaCorreo2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cajitaCorreo2.setForeground(new java.awt.Color(255, 255, 255));
        cajitaCorreo2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajitaCorreo2.setBorder(null);
        cajitaCorreo2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cajitaCorreo2FocusGained(evt);
            }
        });
        cajitaCorreo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajitaCorreo2MousePressed(evt);
            }
        });
        panelRegistrar2.add(cajitaCorreo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 580, 40));

        jSeparator7.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        panelRegistrar2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 580, 10));

        jLabel13.setBackground(new java.awt.Color(255, 102, 102));
        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 102, 102));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("*");
        panelRegistrar2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 390, 30, 30));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Contraseña");
        panelRegistrar2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 580, 30));

        verContrasena2.setOpaque(false);
        verContrasena2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verContrasena2MouseClicked(evt);
            }
        });
        verContrasena2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ojoNoOculto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ojoNoOculto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/atention.png"))); // NOI18N
        verContrasena2.add(ojoNoOculto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 40));

        ojoOculto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ojoOculto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/hide.png"))); // NOI18N
        verContrasena2.add(ojoOculto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 40));

        panelRegistrar2.add(verContrasena2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, 30, 40));

        cajitaContrasena2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cajitaContrasena2.setForeground(new java.awt.Color(255, 255, 255));
        cajitaContrasena2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajitaContrasena2.setBorder(null);
        cajitaContrasena2.setEchoChar('\u25cf');
        cajitaContrasena2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cajitaContrasena2FocusGained(evt);
            }
        });
        cajitaContrasena2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cajitaContrasena2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajitaContrasena2MousePressed(evt);
            }
        });
        panelRegistrar2.add(cajitaContrasena2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 580, 40));

        jSeparator8.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        panelRegistrar2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 580, 10));

        panelAtras2.setBackground(new java.awt.Color(255, 102, 102));
        panelAtras2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAtras2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAtras2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelAtras2MouseExited(evt);
            }
        });
        panelAtras2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAtras2.setBackground(new java.awt.Color(255, 102, 102));
        lblAtras2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblAtras2.setForeground(new java.awt.Color(255, 255, 255));
        lblAtras2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAtras2.setText("Atras");
        lblAtras2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 0), new java.awt.Color(153, 153, 255)));
        panelAtras2.add(lblAtras2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        panelRegistrar2.add(panelAtras2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 110, 30));

        panelRegistrarse2.setBackground(new java.awt.Color(255, 102, 255));
        panelRegistrarse2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRegistrarse2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelRegistrarse2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelRegistrarse2MouseExited(evt);
            }
        });
        panelRegistrarse2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRegistrarse2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblRegistrarse2.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistrarse2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistrarse2.setText("Registrarse");
        lblRegistrarse2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 0), new java.awt.Color(153, 153, 255)));
        panelRegistrarse2.add(lblRegistrarse2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        panelRegistrar2.add(panelRegistrarse2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 520, 110, 30));

        lblRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/registroInterfaz.png"))); // NOI18N
        lblRegistro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(172, 138, 24)));
        lblRegistro.setPreferredSize(new java.awt.Dimension(870, 580));
        panelRegistrar2.add(lblRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelRegistrar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelRegistrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelRegistrar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 5, Short.MAX_VALUE)
                    .addComponent(panelRegistrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 5, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /*---------------------------------------------------------------------------------*/
    private void inicioAbrir() {
        cambiarIcono();
        transparente();

        cajitaCorreo.setText(textoCorreo);
        cajitaContrasena.setText(contraseña);
        VerificarCajaCorreo(cajitaCorreo, cajitaContrasena);
        VerificarCajaContrasena(cajitaCorreo, cajitaContrasena);

        cajitaCorreo.addActionListener(activarTeclado);
        cajitaContrasena.addActionListener(activarTeclado2);
        cajitaCorreo2.addActionListener(activarTeclado3);
        cajitaContrasena2.addActionListener(activarTeclado4);
        cajitaDocumento.addActionListener(activarTeclado5);
        cajitaNombres.addActionListener(activarTeclado6);
        cajitaApellidos.addActionListener(activarTeclado7);

        masestetic(cajitaCorreo, cajitaContrasena);
        panelIconLogin.requestFocus();
        panelRegistrar.setBackground(new Color(0, 0, 0, 0));

    }

    private void cambiarIcono() {
        String rutaImagenIcono = getClass().
                getResource(MisVariables.RUTA_IMAGENES + "/" + MisVariables.ICONO_LOGIN).
                getPath();

        ImageIcon miIcono = new ImageIcon(rutaImagenIcono);
        this.setIconImage(miIcono.getImage());

    }

    public void transparente() {
        ojoNoOculto.setVisible(false);
        ojoNoOculto1.setVisible(false);

        panelRegistrar1.setVisible(false);
        panelRegistrar2.setVisible(false);

        verContrasena.setBackground(new Color(0, 0, 0, 0));
        panelIconLogin.setBackground(new Color(0, 0, 0, 0));
        panelCabecera.setBackground(new Color(0, 0, 0, 0));
        panelIconPassword.setBackground(new Color(0, 0, 0, 0));
        panelIconRegistro.setBackground(new Color(0, 0, 0, 0));
        cajitaContrasena.setBackground(new Color(45, 183, 205, 76));
        cajitaCorreo.setBackground(new Color(45, 183, 205, 76));
        cajitaApellidos.setBackground(new Color(45, 183, 205, 76));
        cajitaContrasena2.setBackground(new Color(45, 183, 205, 76));
        cajitaCorreo2.setBackground(new Color(45, 183, 205, 76));
        cajitaDocumento.setBackground(new Color(45, 183, 205, 76));
        cajitaFecha.setBackground(new Color(45, 183, 205, 76));
        cajitaNombres.setBackground(new Color(45, 183, 205, 76));

    }

    public void borrar() {
        cajitaApellidos.setText("");
        cajitaContrasena.setText("");
        cajitaContrasena2.setText("");
        cajitaCorreo.setText("");
        cajitaCorreo2.setText("");
        cajitaDocumento.setText("");
        cajitaNombres.setText("");
        cajitaFecha.setDate(null);
    }

    public void borrar2() {
        cajitaApellidos.setText("");
        cajitaContrasena2.setText("");
        cajitaCorreo2.setText("");
        cajitaDocumento.setText("");
        cajitaNombres.setText("");
        cajitaFecha.setDate(null);
    }

    /*-------------------------------------------------------------------------------*/
    public void masestetic(JTextField correo, JPasswordField contrasena) {

        VerificarCajaCorreo(correo, contrasena);

        if (correo.getText().isEmpty()) {
            correo.setText(textoCorreo);
            correo.setForeground(new Color(134, 247, 233));
        }
    }

    public void verificar_registro() {

        cajitaDocumento.setText(textoDocumento);
        cajitaNombres.setText(textoNombres);
        cajitaApellidos.setText(textoApellidos);

    }

    private boolean correoValidoMano(String quieroValidarlo) {
        boolean bandera;
        Matcher analizar = correoValido.matcher(quieroValidarlo);
        bandera = analizar.matches();
        return bandera;
    }

    private void VerificarCajaCorreo(JTextField correo, JPasswordField contrasena) {
        if (correo.getText().equals(textoCorreo)) {
            correo.setText("");
            correo.setForeground(new Color(255, 255, 255));

        }
        if (String.valueOf(contrasena.getPassword()).isEmpty()) {
            contrasena.setText(contraseña);
            contrasena.setForeground(new Color(134, 247, 233));
        }
    }

    private void VerificarCajaContrasena(JTextField correo, JPasswordField contrasena) {
        if (String.valueOf(contrasena.getPassword()).equals(contraseña)) {
            contrasena.setText("");
            contrasena.setForeground(new Color(255, 255, 255));
        }
        if (correo.getText().isEmpty()) {
            correo.setText(textoCorreo);
            correo.setForeground(new Color(134, 247, 233));
        }
    }

    private void VerificarRegistro(JTextField Principal, JTextField otro1, JTextField otro2) {
        if (Principal.getText().equals(textoDocumento) || Principal.getText().equals(textoNombres)
                || Principal.getText().equals(textoApellidos)) {
            Principal.setText("");
            Principal.setForeground(new Color(255, 255, 255));
        }

        if (otro1.getText().isEmpty() && otro2.getText().isEmpty()) {
            if (otro1 == cajitaNombres && otro2 == cajitaApellidos) {
                otro1.setText(textoNombres);
                otro2.setText(textoApellidos);

            }
            if (otro1 == cajitaDocumento && otro2 == cajitaApellidos) {
                otro1.setText(textoDocumento);
                otro2.setText(textoApellidos);

            }
            if (otro1 == cajitaDocumento && otro2 == cajitaNombres) {
                otro1.setText(textoDocumento);
                otro2.setText(textoNombres);

            }

            otro1.setForeground(new Color(134, 247, 233));
            otro2.setForeground(new Color(134, 247, 233));

        } else if (otro1.getText().isEmpty()) {
            if (otro1 == cajitaNombres) {

                otro1.setText(textoNombres);
            }
            if (otro1 == cajitaDocumento) {

                otro1.setText(textoDocumento);
            }

            otro1.setForeground(new Color(134, 247, 233));

        } else if (otro2.getText().isEmpty()) {
            if (otro2 == cajitaNombres) {

                otro2.setText(textoNombres);
            }
            if (otro2 == cajitaApellidos) {

                otro2.setText(textoApellidos);
            }

            otro2.setForeground(new Color(134, 247, 233));
        }
    }

    private void VerificarYaAcabe(JTextField correo, JPasswordField contrasena, JPanel entrada) {
        try {
            if (correo.getText().equals("")) {
                correo.setText(textoCorreo);
                correo.setForeground(new Color(134, 247, 233));
                entrada.requestFocus();

            }

            if (String.valueOf(cajitaContrasena.getPassword()).equals("")) {
                contrasena.setText(contraseña);
                contrasena.setForeground(new Color(134, 247, 233));
                entrada.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(entrada, "Completa todos los campos de información", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }

    }

    /*----------------------------------------------------------------------------------------*/
    private void AceptarPanel2(JTextField correo, JPasswordField contrasena, JPanel entrada) {

        String correoTexto, contrasenaTexto;

        VerificarYaAcabe(correo, contrasena, entrada);

        contrasenaTexto = String.valueOf(contrasena.getPassword());
        correoTexto = correo.getText();

        if (correo.getText().equals(textoCorreo) || contrasenaTexto.equals(contraseña) || contrasenaTexto.isEmpty()) {
            JOptionPane.showMessageDialog(entrada, "Completa todos los campos de información", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {

            if (correoValidoMano(cajitaCorreo.getText()) || correo == cajitaCorreo) {
                String claveCifrada = Seguridad.obtenerHash(contrasenaTexto, misConstantes.MI_PIZCA_DE_CONTRASENNA);
                String correoCifrado = Seguridad.obtenerHash(correoTexto, misConstantes.MI_PIZCA_DE_CORREO);
                Acceso objAcceso = new Acceso();
                AccesosDAO objAccesDao = new AccesosDAO();

                objAcceso.setCorreoAcceso(correoCifrado);
                objAcceso.setClaveAcceso(claveCifrada);

                if (objAccesDao.verificarUsuarios("", objAcceso)) {

                    Principal princi = new Principal();

                    princi.setVisible(true);
                    Principal.recibirContrasena.setText(claveCifrada);
                    Principal.recibirCorreo.setText(correoCifrado);
                    this.dispose();

                } else {
                    JOptionPane.showMessageDialog(panelPrincipal, "Datos incorrectos, intentalo nuevamente", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
    }

    private void AceptarPanel(JTextField correo, JPasswordField contrasena, JPanel entrada) {

        String correoTexto, contrasenaTexto;

        VerificarYaAcabe(correo, contrasena, entrada);

        contrasenaTexto = String.valueOf(contrasena.getPassword());
        correoTexto = correo.getText();

        if (correoValidoMano(cajitaCorreo2.getText()) && correo == cajitaCorreo2) {

            String documentoUsuario, nombresUsuario, apellidosUsuario;
            documentoUsuario = cajitaDocumento.getText();
            nombresUsuario = cajitaNombres.getText();
            apellidosUsuario = cajitaApellidos.getText();

            String claveCifrada = Seguridad.obtenerHash(contrasenaTexto, misConstantes.MI_PIZCA_DE_CONTRASENNA);
            String correoCifrado = Seguridad.obtenerHash(correoTexto, misConstantes.MI_PIZCA_DE_CORREO);
            String documentoCifrado = Seguridad.obtenerHash(documentoUsuario, misConstantes.MI_PIZCA_DE_DOCUMENTO);
            String nombreCifrado = Seguridad.obtenerHash(nombresUsuario, misConstantes.MI_PIZCA_DE_NOMBRES);
            String apellidoCifrado = Seguridad.obtenerHash(apellidosUsuario, misConstantes.MI_PIZCA_DE_APELLIDOS);

            AccesosDAO objDAOAcces = new AccesosDAO();
            Usuarios miUser = new Usuarios(0, documentoCifrado, nombreCifrado, apellidoCifrado, null);
            Acceso objAcces = new Acceso(miUser, correoCifrado, claveCifrada);

            if (objDAOAcces.agregar(objAcces)) {
                registrarse();

            }
        } else {
            JOptionPane.showMessageDialog(panelPrincipal, "Datos incorrectos, intentalo nuevamente", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

    }

    /*--------------------------------------------------------------------------------*/

    private void panelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCerrarMouseClicked
        int opcion;
        String opcionesBotones[] = {"Salir", "Cancelar"};
        opcion = JOptionPane.showOptionDialog(panelPrincipal, "¿Esta seguro que desea cerrar la aplicación?",
                "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
                null, opcionesBotones, opcionesBotones[0]);
        if (opcion == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_panelCerrarMouseClicked

    private void panelCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCerrarMouseExited

        lblCerrar1_2.setVisible(false);
        lblCerrar1.setVisible(true);
        panelCerrar.setBackground(new Color(172, 138, 24));

    }//GEN-LAST:event_panelCerrarMouseExited

    private void panelCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCerrarMouseEntered

        lblCerrar1.setVisible(false);
        lblCerrar1_2.setVisible(true);
        panelCerrar.setBackground(new Color(226, 66, 66));

    }//GEN-LAST:event_panelCerrarMouseEntered

    private void panelMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMinimizarMouseEntered
        lblMinimizar1.setVisible(false);
        lblMinimizar1_2.setVisible(true);
        panelMinimizar.setBackground(new Color(137, 110, 21));
    }//GEN-LAST:event_panelMinimizarMouseEntered

    private void panelMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMinimizarMouseExited

        lblMinimizar1.setVisible(true);
        lblMinimizar1_2.setVisible(false);
        panelMinimizar.setBackground(new Color(172, 138, 24));

    }//GEN-LAST:event_panelMinimizarMouseExited

    @SuppressWarnings("empty-statement")
    private void verContrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verContrasenaMouseClicked

        count++;

        if (count % 2 == 0) {
            ojoOculto.setVisible(true);
            ojoNoOculto.setVisible(false);
            cajitaContrasena.setEchoChar('\u25cf');
        } else {
            ojoOculto.setVisible(false);
            ojoNoOculto.setVisible(true);
            cajitaContrasena.setEchoChar((char) 0);
        }

    }//GEN-LAST:event_verContrasenaMouseClicked

    private void panelMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_panelMinimizarMouseClicked

    private void panelIniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelIniciarSesionMouseClicked

        AceptarPanel2(cajitaCorreo, cajitaContrasena, panelPrincipal);
    }//GEN-LAST:event_panelIniciarSesionMouseClicked

    private void cajitaCorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cajitaCorreoFocusGained
        VerificarCajaCorreo(cajitaCorreo, cajitaContrasena);
    }//GEN-LAST:event_cajitaCorreoFocusGained

    private void cajitaContrasenaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cajitaContrasenaFocusGained
        VerificarCajaContrasena(cajitaCorreo, cajitaContrasena);
    }//GEN-LAST:event_cajitaContrasenaFocusGained

    private void cajitaCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajitaCorreoMousePressed
        VerificarCajaCorreo(cajitaCorreo, cajitaContrasena);
    }//GEN-LAST:event_cajitaCorreoMousePressed

    private void cajitaContrasenaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajitaContrasenaMousePressed
        VerificarCajaContrasena(cajitaCorreo, cajitaContrasena);
    }//GEN-LAST:event_cajitaContrasenaMousePressed

    private void panelIniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelIniciarSesionMouseEntered

        panelIniciarSesion.setBackground(new Color(212, 51, 181));
    }//GEN-LAST:event_panelIniciarSesionMouseEntered

    private void panelIniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelIniciarSesionMouseExited

        panelIniciarSesion.setBackground(new Color(255, 102, 255));
    }//GEN-LAST:event_panelIniciarSesionMouseExited

    private void panelCabeceraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCabeceraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - posicionX, y - posicionY);
    }//GEN-LAST:event_panelCabeceraMouseDragged

    private void panelCabeceraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCabeceraMousePressed
        posicionX = evt.getX();
        posicionY = evt.getY();
    }//GEN-LAST:event_panelCabeceraMousePressed

    private void panelRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRegistrarMouseEntered

        lblRegistrar.setForeground(Color.WHITE);
        separadorCrear.setForeground(Color.WHITE);
    }//GEN-LAST:event_panelRegistrarMouseEntered

    private void panelRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRegistrarMouseExited

        lblRegistrar.setForeground(new Color(153, 0, 153));
        separadorCrear.setForeground(new Color(153, 0, 153));
    }//GEN-LAST:event_panelRegistrarMouseExited

    private void cajitaContrasena2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cajitaContrasena2FocusGained
        VerificarCajaContrasena(cajitaCorreo2, cajitaContrasena2);
    }//GEN-LAST:event_cajitaContrasena2FocusGained

    private void panelRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRegistrarMouseClicked

        panelRegistrar1.setVisible(true);
        panelPrincipal.setVisible(false);
        panelRegistrar2.setVisible(false);

        panelLogo2.requestFocus();

    }//GEN-LAST:event_panelRegistrarMouseClicked

    private void guardarVariables() {

        documentoUsuarioC = cajitaDocumento.getText();
        nombresUsuarioC = cajitaNombres.getText();
        apellidosUsuarioC = cajitaApellidos.getText();
        fechaTextoC = cajitaFecha.getDate().toString();
    }

    private void btnCrear() throws ParseException {
        String documentoUsuario, nombresUsuario, apellidosUsuario;

        documentoUsuario = cajitaDocumento.getText();
        nombresUsuario = cajitaNombres.getText();
        apellidosUsuario = cajitaApellidos.getText();

        String documentoCifrado = Seguridad.obtenerHash(documentoUsuario, misConstantes.MI_PIZCA_DE_DOCUMENTO);
        String nombreCifrado = Seguridad.obtenerHash(nombresUsuario, misConstantes.MI_PIZCA_DE_NOMBRES);
        String apellidoCifrado = Seguridad.obtenerHash(apellidosUsuario, misConstantes.MI_PIZCA_DE_APELLIDOS);

        ////////////////////////////////////////////////////////////////////////
        String formatoCalendario = "EEE MMM dd HH:mm:ss zzz yyyy";
        //String formatoBaseDatos = "YYYY-MM-DD";

        String fechaTexto = cajitaFecha.getDate().toString();
        SimpleDateFormat formatoViejito = new SimpleDateFormat(formatoCalendario, Locale.ENGLISH);

        Date fechaCalendario = formatoViejito.parse(fechaTexto);

        ////////////////////////////////////////////////////////////////////////
        if (documentoUsuario.isEmpty() || nombresUsuario.isEmpty() || apellidosUsuario.isEmpty() || documentoUsuario.equals(textoDocumento) || nombresUsuario.equals(textoNombres) || apellidosUsuario.equals(textoApellidos)) {

            count3 = 0;

        } else {

            count3++;

            Usuarios obUsuarios = new Usuarios(0, documentoCifrado, nombreCifrado, apellidoCifrado, fechaCalendario);

            UsuariosDAO objDAOUser = new UsuariosDAO();

            if (count3 == 1) {

                if (objDAOUser.agregar(obUsuarios)) {

                    panelRegistrar2.setVisible(true);
                    panelRegistrar1.setVisible(false);
                    panelPrincipal.setVisible(false);

                    panelIconRegistro.requestFocus();

                }
            } else if (count3 > 1) {

                if (!documentoUsuario.equals(documentoUsuarioC) || !nombresUsuario.equals(nombresUsuarioC)
                        || !apellidosUsuario.equals(apellidosUsuarioC) || !fechaTexto.equals(fechaTextoC)) {

                    if (objDAOUser.agregar(obUsuarios)) {

                        panelRegistrar2.setVisible(true);
                        panelRegistrar1.setVisible(false);
                        panelPrincipal.setVisible(false);

                        panelIconRegistro.requestFocus();

                    }
                } else {
                    panelRegistrar2.setVisible(true);
                    panelRegistrar1.setVisible(false);
                    panelPrincipal.setVisible(false);

                    panelIconRegistro.requestFocus();
                }

            }

        }
    }


    private void panelSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSiguienteMouseClicked

        try {
            if (cajitaDocumento.getText().isEmpty() || cajitaNombres.getText().isEmpty() || cajitaApellidos.getText().isEmpty() || cajitaDocumento.getText().equals(textoDocumento) || cajitaNombres.getText().equals(textoNombres) || cajitaApellidos.getText().equals(textoApellidos) || cajitaFecha.getDate() == null) {
                cajitaDocumento.requestFocus();
                count3 = 0;
                JOptionPane.showMessageDialog(panelRegistrar1, "Rellena los datos obligatorios",
                        "Advertencia", JOptionPane.WARNING_MESSAGE);
            } else {
                btnCrear();
            }

        } catch (ParseException ex) {
            System.out.println("ERROR");
        }

    }//GEN-LAST:event_panelSiguienteMouseClicked

    private void panelAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAtrasMouseClicked
        panelPrincipal.setVisible(true);
        panelRegistrar1.setVisible(false);
        panelRegistrar2.setVisible(false);
        borrar2();

        panelLogo.requestFocus();


    }//GEN-LAST:event_panelAtrasMouseClicked

    private void panelAtras2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAtras2MouseClicked
        panelRegistrar1.setVisible(true);
        panelPrincipal.setVisible(false);
        panelRegistrar2.setVisible(false);

        lblTitulo2.requestFocus();
    }//GEN-LAST:event_panelAtras2MouseClicked

    public void registrarse() {
        VerificarYaAcabe(cajitaCorreo2, cajitaContrasena2, panelRegistrarse2);
        panelPrincipal.setVisible(true);
        panelRegistrar1.setVisible(false);
        panelRegistrar2.setVisible(false);
        borrar();
        panelLogo.requestFocus();

    }

    private void panelRegistrarse2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRegistrarse2MouseClicked
        AceptarPanel(cajitaCorreo2, cajitaContrasena2, panelRegistrar2);

    }//GEN-LAST:event_panelRegistrarse2MouseClicked

    private void panelCerrar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCerrar2MouseEntered
        lblCerrar2.setVisible(false);
        lblCerrar2_2.setVisible(true);
        panelCerrar2.setBackground(new Color(226, 66, 66));
    }//GEN-LAST:event_panelCerrar2MouseEntered

    private void panelCerrar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCerrar2MouseExited

        lblCerrar2_2.setVisible(false);
        lblCerrar2.setVisible(true);
        panelCerrar2.setBackground(new Color(172, 138, 24));
    }//GEN-LAST:event_panelCerrar2MouseExited

    private void panelCerrar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCerrar2MouseClicked
        int opcion;
        String opcionesBotones[] = {"Salir", "Cancelar"};
        opcion = JOptionPane.showOptionDialog(panelPrincipal, "¿Esta seguro que desea cerrar la aplicación?",
                "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
                null, opcionesBotones, opcionesBotones[0]);
        if (opcion == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_panelCerrar2MouseClicked

    private void panelCerrar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCerrar3MouseClicked
        int opcion;
        String opcionesBotones[] = {"Salir", "Cancelar"};
        opcion = JOptionPane.showOptionDialog(panelPrincipal, "¿Esta seguro que desea cerrar la aplicación?",
                "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
                null, opcionesBotones, opcionesBotones[0]);
        if (opcion == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_panelCerrar3MouseClicked

    private void panelCerrar3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCerrar3MouseEntered
        lblcerrar3.setVisible(false);
        lblcerrar3_2.setVisible(true);
        panelCerrar3.setBackground(new Color(226, 66, 66));
    }//GEN-LAST:event_panelCerrar3MouseEntered

    private void panelCerrar3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCerrar3MouseExited
        lblcerrar3.setVisible(false);
        lblcerrar3_2.setVisible(true);
        panelCerrar3.setBackground(new Color(172, 138, 24));
    }//GEN-LAST:event_panelCerrar3MouseExited

    private void panelMinimizar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMinimizar2MouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_panelMinimizar2MouseClicked

    private void panelMinimizar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMinimizar2MouseEntered
        lblMinimizar2.setVisible(false);
        lblMinimizar2_2.setVisible(true);
        panelMinimizar2.setBackground(new Color(137, 110, 21));
    }//GEN-LAST:event_panelMinimizar2MouseEntered

    private void panelMinimizar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMinimizar2MouseExited
        lblMinimizar2.setVisible(true);
        lblMinimizar2_2.setVisible(false);
        panelMinimizar2.setBackground(new Color(172, 138, 24));
    }//GEN-LAST:event_panelMinimizar2MouseExited

    private void panelMinimizar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMinimizar3MouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_panelMinimizar3MouseClicked

    private void panelMinimizar3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMinimizar3MouseEntered
        lblMinimizar3.setVisible(false);
        lblMinimizar3_2.setVisible(true);
        panelMinimizar3.setBackground(new Color(137, 110, 21));
    }//GEN-LAST:event_panelMinimizar3MouseEntered

    private void panelMinimizar3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMinimizar3MouseExited
        lblMinimizar3.setVisible(true);
        lblMinimizar3_2.setVisible(false);
        panelMinimizar3.setBackground(new Color(172, 138, 24));
    }//GEN-LAST:event_panelMinimizar3MouseExited

    private void panelAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAtrasMouseEntered

        panelAtras.setBackground(new Color(210, 106, 106));
        lblAtras.setText("<<< Atras");
    }//GEN-LAST:event_panelAtrasMouseEntered

    private void panelAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAtrasMouseExited
        panelAtras.setBackground(new Color(255, 102, 102));
        lblAtras.setText("Atras");
    }//GEN-LAST:event_panelAtrasMouseExited

    private void panelSiguienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSiguienteMouseEntered
        panelSiguiente.setBackground(new Color(226, 177, 29));
        lblSiguiente.setText("Siguiente >>>");
    }//GEN-LAST:event_panelSiguienteMouseEntered

    private void panelSiguienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSiguienteMouseExited
        panelSiguiente.setBackground(new Color(255, 204, 51));
        lblSiguiente.setText("Siguiente");
    }//GEN-LAST:event_panelSiguienteMouseExited

    private void cajitaCorreo2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cajitaCorreo2FocusGained
        VerificarCajaCorreo(cajitaCorreo2, cajitaContrasena2);
    }//GEN-LAST:event_cajitaCorreo2FocusGained

    private void cajitaContrasena2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajitaContrasena2MousePressed
        VerificarCajaContrasena(cajitaCorreo2, cajitaContrasena2);
    }//GEN-LAST:event_cajitaContrasena2MousePressed

    private void cajitaCorreo2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajitaCorreo2MousePressed
        VerificarCajaCorreo(cajitaCorreo2, cajitaContrasena2);
    }//GEN-LAST:event_cajitaCorreo2MousePressed

    private void cajitaContrasena2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajitaContrasena2MouseClicked
        VerificarCajaContrasena(cajitaCorreo2, cajitaContrasena2);
    }//GEN-LAST:event_cajitaContrasena2MouseClicked

    private void panelAtras2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAtras2MouseEntered

        panelAtras2.setBackground(new Color(210, 106, 106));
        lblAtras2.setText("<<< Atras");
    }//GEN-LAST:event_panelAtras2MouseEntered

    private void panelAtras2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAtras2MouseExited
        panelAtras2.setBackground(new Color(255, 102, 102));
        lblAtras2.setText("Atras");
    }//GEN-LAST:event_panelAtras2MouseExited

    private void panelRegistrarse2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRegistrarse2MouseEntered
        lblRegistrarse2.setText("Registrarse");
        panelRegistrarse2.setBackground(new Color(212, 51, 181));
    }//GEN-LAST:event_panelRegistrarse2MouseEntered

    private void panelRegistrarse2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRegistrarse2MouseExited
        lblRegistrarse2.setText("Registrarse");
        panelRegistrarse2.setBackground(new Color(255, 102, 255));
    }//GEN-LAST:event_panelRegistrarse2MouseExited

    private void verContrasena2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verContrasena2MouseClicked

        count2++;
        if (count2 % 2 == 0) {
            ojoOculto1.setVisible(true);
            ojoNoOculto1.setVisible(false);
            cajitaContrasena2.setEchoChar('\u25cf');
        } else {
            ojoOculto1.setVisible(false);
            ojoNoOculto1.setVisible(true);
            cajitaContrasena2.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_verContrasena2MouseClicked

    private void panelIconRegistroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panelIconRegistroFocusGained

        VerificarCajaCorreo(cajitaCorreo2, cajitaContrasena2);
        VerificarCajaContrasena(cajitaCorreo2, cajitaContrasena2);
        masestetic(cajitaCorreo2, cajitaContrasena2);

    }//GEN-LAST:event_panelIconRegistroFocusGained

    private void cajitaDocumentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cajitaDocumentoFocusGained
        VerificarRegistro(cajitaDocumento, cajitaNombres, cajitaApellidos);
    }//GEN-LAST:event_cajitaDocumentoFocusGained

    private void cajitaNombresFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cajitaNombresFocusGained
        VerificarRegistro(cajitaNombres, cajitaDocumento, cajitaApellidos);
    }//GEN-LAST:event_cajitaNombresFocusGained

    private void cajitaApellidosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cajitaApellidosFocusGained
        VerificarRegistro(cajitaApellidos, cajitaDocumento, cajitaNombres);
    }//GEN-LAST:event_cajitaApellidosFocusGained

    private void panelLogo2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panelLogo2FocusGained

        verificar_registro();
        VerificarRegistro(cajitaDocumento, cajitaNombres, cajitaApellidos);
        VerificarRegistro(cajitaNombres, cajitaDocumento, cajitaApellidos);
        VerificarRegistro(cajitaApellidos, cajitaDocumento, cajitaNombres);

        if (cajitaApellidos.getText().isEmpty()) {
            cajitaApellidos.setText(textoApellidos);
            cajitaApellidos.setForeground(new Color(134, 247, 233));
        }

        lblIconRegistro.requestFocus();
    }//GEN-LAST:event_panelLogo2FocusGained

    private void cajitaDocumentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajitaDocumentoMousePressed
        VerificarRegistro(cajitaDocumento, cajitaNombres, cajitaApellidos);
    }//GEN-LAST:event_cajitaDocumentoMousePressed

    private void cajitaNombresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajitaNombresMousePressed
        VerificarRegistro(cajitaNombres, cajitaDocumento, cajitaApellidos);
    }//GEN-LAST:event_cajitaNombresMousePressed

    private void cajitaApellidosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajitaApellidosMousePressed
        VerificarRegistro(cajitaApellidos, cajitaDocumento, cajitaNombres);
    }//GEN-LAST:event_cajitaApellidosMousePressed

    private void panelLogoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panelLogoFocusGained
        inicioAbrir();
    }//GEN-LAST:event_panelLogoFocusGained

    private void lblTitulo2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblTitulo2FocusGained
        if (cajitaDocumento.getText().isEmpty()) {
            cajitaDocumento.setText(textoDocumento);
            cajitaDocumento.setForeground(new Color(134, 247, 233));
        }
        guardarVariables();
        lblIconRegistro.requestFocus();
    }//GEN-LAST:event_lblTitulo2FocusGained

    private void PanelCabecera2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelCabecera2MousePressed
        posicionX = evt.getX();
        posicionY = evt.getY();
    }//GEN-LAST:event_PanelCabecera2MousePressed

    private void PanelCabecera2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelCabecera2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - posicionX, y - posicionY);
    }//GEN-LAST:event_PanelCabecera2MouseDragged

    private void panelCabcera3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCabcera3MousePressed
        posicionX = evt.getX();
        posicionY = evt.getY();
    }//GEN-LAST:event_panelCabcera3MousePressed

    private void panelCabcera3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCabcera3MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - posicionX, y - posicionY);
    }//GEN-LAST:event_panelCabcera3MouseDragged

    /*---------------------------------------------------------------------------*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });

        /**
         *
         */
        /**
         *
         */
        /**
         *
         */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Fondo2;
    private javax.swing.JPanel PanelCabecera2;
    private javax.swing.JTextField cajitaApellidos;
    private javax.swing.JPasswordField cajitaContrasena;
    private javax.swing.JPasswordField cajitaContrasena2;
    private javax.swing.JTextField cajitaCorreo;
    private javax.swing.JTextField cajitaCorreo2;
    private javax.swing.JTextField cajitaDocumento;
    private com.toedter.calendar.JDateChooser cajitaFecha;
    private javax.swing.JTextField cajitaNombres;
    private javax.swing.JLabel iconLogo;
    private javax.swing.JLabel iconPassword;
    private javax.swing.JLabel iconUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblAtras;
    private javax.swing.JLabel lblAtras2;
    private javax.swing.JLabel lblCerrar1;
    private javax.swing.JLabel lblCerrar1_2;
    private javax.swing.JLabel lblCerrar2;
    private javax.swing.JLabel lblCerrar2_2;
    private javax.swing.JLabel lblIconRegistro;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogo3;
    private javax.swing.JLabel lblMinimizar1;
    private javax.swing.JLabel lblMinimizar1_2;
    private javax.swing.JLabel lblMinimizar2;
    private javax.swing.JLabel lblMinimizar2_2;
    private javax.swing.JLabel lblMinimizar3;
    private javax.swing.JLabel lblMinimizar3_2;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JLabel lblRegistrarse2;
    private javax.swing.JLabel lblRegistro;
    private javax.swing.JLabel lblSiguiente;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblTitulo3;
    private javax.swing.JLabel lblcerrar3;
    private javax.swing.JLabel lblcerrar3_2;
    private javax.swing.JLabel ojoNoOculto;
    private javax.swing.JLabel ojoNoOculto1;
    private javax.swing.JLabel ojoOculto;
    private javax.swing.JLabel ojoOculto1;
    private javax.swing.JPanel panelAtras;
    private javax.swing.JPanel panelAtras2;
    private javax.swing.JPanel panelCabcera3;
    private javax.swing.JPanel panelCabecera;
    private javax.swing.JPanel panelCerrar;
    private javax.swing.JPanel panelCerrar2;
    private javax.swing.JPanel panelCerrar3;
    private javax.swing.JPanel panelIconLogin;
    private javax.swing.JPanel panelIconPassword;
    private javax.swing.JPanel panelIconRegistro;
    private javax.swing.JPanel panelIniciarSesion;
    private javax.swing.JPanel panelLogo;
    private javax.swing.JPanel panelLogo2;
    private javax.swing.JPanel panelLogo3;
    private javax.swing.JPanel panelMinimizar;
    private javax.swing.JPanel panelMinimizar2;
    private javax.swing.JPanel panelMinimizar3;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelRegistrar;
    private javax.swing.JPanel panelRegistrar1;
    private javax.swing.JPanel panelRegistrar2;
    private javax.swing.JPanel panelRegistrarse2;
    private javax.swing.JPanel panelSiguiente;
    private javax.swing.JSeparator separadorCrear;
    private javax.swing.JPanel verContrasena;
    private javax.swing.JPanel verContrasena2;
    // End of variables declaration//GEN-END:variables
}
