/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.project.formularios;

import com.project.configuraciones.MisVariables;
import com.project.daos.ContrasenasGuardadasDAO;
import com.project.modelos.Acceso;
import com.project.modelos.ContrasenasGuardadas;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author santi
 */
public final class Principal extends javax.swing.JFrame {

    int count, count2;

    private int posicionX;
    private int posicionY;

    private final Map<Integer, Integer> codigoNombre = new HashMap<>();

    private final DefaultComboBoxModel miModeloNombre = new DefaultComboBoxModel();

    Action activarTeclado = new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent evento) {
            MouseEvent evt = null;
            panelBuscadorMouseClicked(evt);
        }
    };

    Action activarTeclado2 = new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent evento) {
            MouseEvent evt = null;
            cajitaNombredeUsuario.requestFocus();
        }
    };

    Action activarTeclado3 = new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent evento) {
            MouseEvent evt = null;
            cajitaContrasena.requestFocus();
        }
    };

    Action activarTeclado4 = new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent evento) {
            MouseEvent evt = null;
            cajitaURL.requestFocus();
        }
    };

    Action activarTeclado5 = new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent evento) {
            MouseEvent evt = null;
            cajitaURL2.requestFocus();
        }
    };
    Action activarTeclado6 = new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent evento) {
            MouseEvent evt = null;
            cajitaNombreUsuario2.requestFocus();
        }
    };
    Action activarTeclado7 = new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent evento) {
            MouseEvent evt = null;
            cajitaContrasena2.requestFocus();
        }
    };
    Action activarTeclado8 = new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent evento) {
            MouseEvent evt = null;
            cajitaNombreWeb2.requestFocus();
        }
    };

    public Principal() {
        initComponents();

        cambiarIcono();
        panelPopap.setVisible(false);
        transparente();
        buscadorTxt.addActionListener(activarTeclado);
        cajitaURL.addActionListener(activarTeclado2);
        cajitaNombredeUsuario.addActionListener(activarTeclado3);
        cajitaContrasena.addActionListener(activarTeclado4);
        cajitaNombreWeb2.addActionListener(activarTeclado5);
        cajitaURL2.addActionListener(activarTeclado6);
        cajitaNombreUsuario2.addActionListener(activarTeclado7);
        cajitaContrasena2.addActionListener(activarTeclado8);
        PanelLogin.requestFocus();

        ojoNoOculto1.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        PanelLogin = new javax.swing.JPanel();
        iconLogin = new javax.swing.JLabel();
        panelCabecera = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panelCerrar = new javax.swing.JPanel();
        iconCerrar2 = new javax.swing.JLabel();
        iconCerrar = new javax.swing.JLabel();
        panelMinimizar = new javax.swing.JPanel();
        iconMinimizar = new javax.swing.JLabel();
        iconMinimizar2 = new javax.swing.JLabel();
        lblBuscador = new javax.swing.JLabel();
        buscadorTxt = new javax.swing.JTextField();
        comboBuscador = new javax.swing.JComboBox<>();
        panelBuscador = new javax.swing.JPanel();
        iconBuscador = new javax.swing.JLabel();
        lblActualizacion = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lblURL = new javax.swing.JLabel();
        cajitaURL = new javax.swing.JTextField();
        copiarUrl = new javax.swing.JButton();
        txtCopy1 = new javax.swing.JLabel();
        separadorURL = new javax.swing.JSeparator();
        lblNombreUsuario = new javax.swing.JLabel();
        cajitaNombredeUsuario = new javax.swing.JTextField();
        copiarU = new javax.swing.JButton();
        txtCopy2 = new javax.swing.JLabel();
        separadorNombreUsuario = new javax.swing.JSeparator();
        lblContrasena = new javax.swing.JLabel();
        verContrasena1 = new javax.swing.JPanel();
        ojoNoOculto1 = new javax.swing.JLabel();
        ojoOculto1 = new javax.swing.JLabel();
        miremos = new javax.swing.JTextField();
        cajitaContrasena = new javax.swing.JTextField();
        CopiarC = new javax.swing.JButton();
        txtCopy3 = new javax.swing.JLabel();
        separadorContraseña = new javax.swing.JSeparator();
        lblUrl = new javax.swing.JLabel();
        lblNombreUsu = new javax.swing.JLabel();
        lblContrasenna = new javax.swing.JLabel();
        panelAgregar = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JLabel();
        panelActualizar = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JLabel();
        panelBorrar = new javax.swing.JPanel();
        btnBorrar = new javax.swing.JLabel();
        interfazPrincipal = new javax.swing.JLabel();
        recibirCorreo = new javax.swing.JTextField();
        recibirContrasena = new javax.swing.JTextField();
        panelPopap = new javax.swing.JPanel();
        panelCabecera2 = new javax.swing.JPanel();
        panelLogo2 = new javax.swing.JPanel();
        lblLogo2 = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        panelMinimizar2 = new javax.swing.JPanel();
        lblMinimizar2 = new javax.swing.JLabel();
        lblMinimizar2_2 = new javax.swing.JLabel();
        panelDevolver = new javax.swing.JPanel();
        iconDevolver = new javax.swing.JLabel();
        iconDevolver2 = new javax.swing.JLabel();
        iconDevolver3 = new javax.swing.JLabel();
        lblAgregar = new javax.swing.JLabel();
        lblNombreWeb = new javax.swing.JLabel();
        cajitaNombreWeb2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblUrl3 = new javax.swing.JLabel();
        cajitaURL2 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblNameUsu = new javax.swing.JLabel();
        cajitaNombreUsuario2 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblcontra = new javax.swing.JLabel();
        verContrasena = new javax.swing.JPanel();
        ojoNoOculto = new javax.swing.JLabel();
        ojoOculto = new javax.swing.JLabel();
        cajitaContrasena2 = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        panelAdd = new javax.swing.JPanel();
        txtAgregarContraseña = new javax.swing.JLabel();
        interfazAgregarContraseña = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        panelPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelPrincipal.setDoubleBuffered(false);
        panelPrincipal.setMinimumSize(new java.awt.Dimension(870, 580));
        panelPrincipal.setPreferredSize(new java.awt.Dimension(870, 580));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelLogin.setBackground(new java.awt.Color(172, 138, 24));
        PanelLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PanelLoginFocusGained(evt);
            }
        });
        PanelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/logoChiqui2.png"))); // NOI18N
        PanelLogin.add(iconLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        panelPrincipal.add(PanelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        panelCabecera.setBackground(new java.awt.Color(172, 138, 24));
        panelCabecera.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelCabeceraMouseDragged(evt);
            }
        });
        panelCabecera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelCabeceraMousePressed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("MEPASS");

        panelCerrar.setBackground(new java.awt.Color(172, 138, 24));
        panelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelCerrarMouseExited(evt);
            }
        });
        panelCerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconCerrar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconCerrar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/cerrar2.png"))); // NOI18N
        panelCerrar.add(iconCerrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        iconCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/cerrar.png"))); // NOI18N
        panelCerrar.add(iconCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        panelMinimizar.setBackground(new java.awt.Color(172, 138, 24));
        panelMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelMinimizarMouseExited(evt);
            }
        });
        panelMinimizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/menos.png"))); // NOI18N
        panelMinimizar.add(iconMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        iconMinimizar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconMinimizar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/menos2.png"))); // NOI18N
        panelMinimizar.add(iconMinimizar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        javax.swing.GroupLayout panelCabeceraLayout = new javax.swing.GroupLayout(panelCabecera);
        panelCabecera.setLayout(panelCabeceraLayout);
        panelCabeceraLayout.setHorizontalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabeceraLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 640, Short.MAX_VALUE)
                .addComponent(panelMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelCabeceraLayout.setVerticalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabeceraLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCabeceraLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelMinimizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panelPrincipal.add(panelCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 50));

        lblBuscador.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblBuscador.setForeground(new java.awt.Color(102, 102, 102));
        lblBuscador.setText("--- Buscador : -----------------------------------------------------------------------");
        panelPrincipal.add(lblBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 230, -1, 20));

        buscadorTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        buscadorTxt.setForeground(new java.awt.Color(51, 51, 51));
        buscadorTxt.setBorder(null);
        buscadorTxt.setMinimumSize(new java.awt.Dimension(66, 18));
        buscadorTxt.setPreferredSize(new java.awt.Dimension(66, 18));
        buscadorTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                buscadorTxtFocusGained(evt);
            }
        });
        buscadorTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscadorTxtMouseClicked(evt);
            }
        });
        panelPrincipal.add(buscadorTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 340, 40));

        comboBuscador.setBackground(new java.awt.Color(255, 204, 51));
        comboBuscador.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        comboBuscador.setForeground(new java.awt.Color(51, 51, 51));
        comboBuscador.setBorder(null);
        comboBuscador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboBuscador.setName(""); // NOI18N
        comboBuscador.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBuscadorItemStateChanged(evt);
            }
        });
        comboBuscador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                comboBuscadorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                comboBuscadorFocusLost(evt);
            }
        });
        panelPrincipal.add(comboBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 370, 40));

        panelBuscador.setBackground(new java.awt.Color(255, 204, 51));
        panelBuscador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelBuscador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelBuscadorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelBuscadorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelBuscadorMouseExited(evt);
            }
        });

        iconBuscador.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        iconBuscador.setForeground(new java.awt.Color(255, 255, 255));
        iconBuscador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconBuscador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/investigar.png"))); // NOI18N
        iconBuscador.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 0), new java.awt.Color(153, 153, 255)));

        javax.swing.GroupLayout panelBuscadorLayout = new javax.swing.GroupLayout(panelBuscador);
        panelBuscador.setLayout(panelBuscadorLayout);
        panelBuscadorLayout.setHorizontalGroup(
            panelBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuscadorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(iconBuscador))
        );
        panelBuscadorLayout.setVerticalGroup(
            panelBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconBuscador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, 40, 40));

        lblActualizacion.setBackground(new java.awt.Color(255, 51, 51));
        lblActualizacion.setFont(new java.awt.Font("Trebuchet MS", 2, 12)); // NOI18N
        lblActualizacion.setForeground(new java.awt.Color(255, 102, 102));
        panelPrincipal.add(lblActualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 330, 20));

        lblname.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblname.setForeground(new java.awt.Color(255, 255, 255));
        lblname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblname.setText("Seleccione una contraseña -->");
        lblname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true));
        panelPrincipal.add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 330, 40));

        lblURL.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblURL.setForeground(new java.awt.Color(255, 255, 255));
        lblURL.setText("URL de la página ->");
        panelPrincipal.add(lblURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 130, 40));

        cajitaURL.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cajitaURL.setForeground(new java.awt.Color(255, 255, 255));
        cajitaURL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajitaURL.setBorder(null);
        cajitaURL.setDoubleBuffered(true);
        panelPrincipal.add(cajitaURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 580, 40));

        copiarUrl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/copy (2).png"))); // NOI18N
        copiarUrl.setBorder(new javax.swing.border.LineBorder(java.awt.Color.orange, 1, true));
        copiarUrl.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                copiarUrlFocusLost(evt);
            }
        });
        copiarUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiarUrlActionPerformed(evt);
            }
        });
        panelPrincipal.add(copiarUrl, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 310, 40, 40));

        txtCopy1.setForeground(new java.awt.Color(102, 102, 102));
        txtCopy1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCopy1.setText("TEXTO COPIADO");
        panelPrincipal.add(txtCopy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 580, -1));

        separadorURL.setBackground(new java.awt.Color(255, 255, 255));
        separadorURL.setForeground(new java.awt.Color(255, 255, 255));
        panelPrincipal.add(separadorURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 580, 10));

        lblNombreUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreUsuario.setText("Nombre Usuario ->");
        panelPrincipal.add(lblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 130, 40));

        cajitaNombredeUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cajitaNombredeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        cajitaNombredeUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajitaNombredeUsuario.setBorder(null);
        panelPrincipal.add(cajitaNombredeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 580, 40));

        copiarU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/copy (2).png"))); // NOI18N
        copiarU.setBorder(new javax.swing.border.LineBorder(java.awt.Color.orange, 1, true));
        copiarU.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                copiarUFocusLost(evt);
            }
        });
        copiarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiarUActionPerformed(evt);
            }
        });
        panelPrincipal.add(copiarU, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 40, 40));

        txtCopy2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        txtCopy2.setForeground(new java.awt.Color(102, 102, 102));
        txtCopy2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCopy2.setText("TEXTO COPIADO");
        panelPrincipal.add(txtCopy2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 580, -1));

        separadorNombreUsuario.setBackground(new java.awt.Color(255, 255, 255));
        separadorNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        panelPrincipal.add(separadorNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 580, 10));

        lblContrasena.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblContrasena.setForeground(new java.awt.Color(255, 255, 255));
        lblContrasena.setText("Contraseña ------->");
        panelPrincipal.add(lblContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 130, 40));

        verContrasena1.setOpaque(false);
        verContrasena1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verContrasena1MouseClicked(evt);
            }
        });
        verContrasena1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ojoNoOculto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ojoNoOculto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/atention.png"))); // NOI18N
        verContrasena1.add(ojoNoOculto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        ojoOculto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ojoOculto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/hide.png"))); // NOI18N
        verContrasena1.add(ojoOculto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        panelPrincipal.add(verContrasena1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 450, 40, 40));

        miremos.setEditable(false);
        miremos.setBackground(new java.awt.Color(234, 107, 107));
        miremos.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        miremos.setForeground(new java.awt.Color(255, 255, 255));
        miremos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        miremos.setText("||||||||||-------------> Contraseña Secreta <-------------||||||||||||");
        panelPrincipal.add(miremos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 454, 520, 32));

        cajitaContrasena.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cajitaContrasena.setForeground(new java.awt.Color(255, 255, 255));
        cajitaContrasena.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajitaContrasena.setBorder(null);
        panelPrincipal.add(cajitaContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 580, 40));

        CopiarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/copy (2).png"))); // NOI18N
        CopiarC.setBorder(new javax.swing.border.LineBorder(java.awt.Color.orange, 1, true));
        CopiarC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CopiarCFocusLost(evt);
            }
        });
        CopiarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CopiarCActionPerformed(evt);
            }
        });
        panelPrincipal.add(CopiarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 450, 40, 40));

        txtCopy3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        txtCopy3.setForeground(new java.awt.Color(102, 102, 102));
        txtCopy3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCopy3.setText("TEXTO COPIADO");
        panelPrincipal.add(txtCopy3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 580, -1));

        separadorContraseña.setBackground(new java.awt.Color(255, 255, 255));
        separadorContraseña.setForeground(new java.awt.Color(255, 255, 255));
        panelPrincipal.add(separadorContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 580, 10));
        panelPrincipal.add(lblUrl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));
        panelPrincipal.add(lblNombreUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));
        panelPrincipal.add(lblContrasenna, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        panelAgregar.setBackground(new java.awt.Color(255, 102, 255));
        panelAgregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelAgregarMouseExited(evt);
            }
        });
        panelAgregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAgregar.setText("Agregar Contraseña");
        btnAgregar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 0), new java.awt.Color(153, 153, 255)));
        panelAgregar.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        panelPrincipal.add(panelAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 140, 30));

        panelActualizar.setBackground(new java.awt.Color(102, 204, 255));
        panelActualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelActualizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelActualizarMouseExited(evt);
            }
        });
        panelActualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnActualizar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 0), new java.awt.Color(153, 153, 255)));
        btnActualizar.setPreferredSize(new java.awt.Dimension(50, 30));
        panelActualizar.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        panelPrincipal.add(panelActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 520, -1, 30));

        panelBorrar.setBackground(new java.awt.Color(255, 102, 102));
        panelBorrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelBorrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelBorrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelBorrarMouseExited(evt);
            }
        });
        panelBorrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBorrar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBorrar.setText("Borrar");
        btnBorrar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 0), new java.awt.Color(153, 153, 255)));
        panelBorrar.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        panelPrincipal.add(panelBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 520, -1, 30));

        interfazPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/interfazPrincipal.png"))); // NOI18N
        panelPrincipal.add(interfazPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 580));

        recibirCorreo.setEditable(false);
        recibirCorreo.setToolTipText("");
        panelPrincipal.add(recibirCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        recibirContrasena.setEditable(false);
        recibirContrasena.setToolTipText("");
        panelPrincipal.add(recibirContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        panelPopap.setMinimumSize(new java.awt.Dimension(870, 580));
        panelPopap.setPreferredSize(new java.awt.Dimension(870, 580));
        panelPopap.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCabecera2.setBackground(new java.awt.Color(172, 138, 24));
        panelCabecera2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelCabecera2MouseDragged(evt);
            }
        });
        panelCabecera2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelCabecera2MousePressed(evt);
            }
        });
        panelCabecera2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLogo2.setBackground(new java.awt.Color(172, 138, 24));
        panelLogo2.setPreferredSize(new java.awt.Dimension(50, 34));
        panelLogo2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/logoChiqui2.png"))); // NOI18N
        panelLogo2.add(lblLogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        panelCabecera2.add(panelLogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        lblTitulo2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo2.setText("MEPASS");
        panelCabecera2.add(lblTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        panelMinimizar2.setBackground(new java.awt.Color(172, 138, 24));
        panelMinimizar2.setPreferredSize(new java.awt.Dimension(50, 34));
        panelMinimizar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMinimizar2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelMinimizar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelMinimizar2MouseExited(evt);
            }
        });
        panelMinimizar2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMinimizar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimizar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/menos.png"))); // NOI18N
        panelMinimizar2.add(lblMinimizar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        lblMinimizar2_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimizar2_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/menos2.png"))); // NOI18N
        panelMinimizar2.add(lblMinimizar2_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        panelCabecera2.add(panelMinimizar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 60, 50));

        panelPopap.add(panelCabecera2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 50));

        panelDevolver.setBackground(new java.awt.Color(0, 204, 204));
        panelDevolver.setOpaque(false);
        panelDevolver.setPreferredSize(new java.awt.Dimension(50, 34));
        panelDevolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelDevolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelDevolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelDevolverMouseExited(evt);
            }
        });
        panelDevolver.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconDevolver.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        iconDevolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/devolverse2.png"))); // NOI18N
        panelDevolver.add(iconDevolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 40));

        iconDevolver2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/devolverse.gif"))); // NOI18N
        panelDevolver.add(iconDevolver2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        iconDevolver3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/devolverse.gif"))); // NOI18N
        panelDevolver.add(iconDevolver3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 0, 40, 40));

        panelPopap.add(panelDevolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 90, 40));
        panelDevolver.getAccessibleContext().setAccessibleName("");

        lblAgregar.setFont(new java.awt.Font("Trebuchet MS", 2, 12)); // NOI18N
        lblAgregar.setForeground(new java.awt.Color(255, 102, 102));
        lblAgregar.setToolTipText("");
        lblAgregar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblAgregarFocusLost(evt);
            }
        });
        panelPopap.add(lblAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 570, 20));

        lblNombreWeb.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblNombreWeb.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreWeb.setText("Nombre web o aplicación");
        panelPopap.add(lblNombreWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 570, 30));

        cajitaNombreWeb2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cajitaNombreWeb2.setForeground(new java.awt.Color(255, 255, 255));
        cajitaNombreWeb2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajitaNombreWeb2.setBorder(null);
        panelPopap.add(cajitaNombreWeb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 570, 40));
        cajitaNombreWeb2.getAccessibleContext().setAccessibleName("");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        panelPopap.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 570, 10));
        jSeparator1.getAccessibleContext().setAccessibleName("");

        lblUrl3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUrl3.setForeground(new java.awt.Color(255, 255, 255));
        lblUrl3.setText("Url de la web o aplicación");
        panelPopap.add(lblUrl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 570, 30));

        cajitaURL2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cajitaURL2.setForeground(new java.awt.Color(255, 255, 255));
        cajitaURL2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajitaURL2.setBorder(null);
        panelPopap.add(cajitaURL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 570, 40));
        cajitaURL2.getAccessibleContext().setAccessibleName("");

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        panelPopap.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 570, 10));
        jSeparator2.getAccessibleContext().setAccessibleName("");

        lblNameUsu.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblNameUsu.setForeground(new java.awt.Color(255, 255, 255));
        lblNameUsu.setText("Nombre del usuario");
        panelPopap.add(lblNameUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 570, 30));

        cajitaNombreUsuario2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cajitaNombreUsuario2.setForeground(new java.awt.Color(255, 255, 255));
        cajitaNombreUsuario2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajitaNombreUsuario2.setBorder(null);
        panelPopap.add(cajitaNombreUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 570, 40));
        cajitaNombreUsuario2.getAccessibleContext().setAccessibleName("");

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        panelPopap.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 570, 10));

        lblcontra.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblcontra.setForeground(new java.awt.Color(255, 255, 255));
        lblcontra.setText("Contraseña");
        panelPopap.add(lblcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 570, 30));

        verContrasena.setOpaque(false);
        verContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verContrasenaMouseClicked(evt);
            }
        });
        verContrasena.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ojoNoOculto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ojoNoOculto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/atention.png"))); // NOI18N
        verContrasena.add(ojoNoOculto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        ojoOculto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ojoOculto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/hide.png"))); // NOI18N
        verContrasena.add(ojoOculto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        panelPopap.add(verContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 470, 40, 40));
        verContrasena.getAccessibleContext().setAccessibleName("");

        cajitaContrasena2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cajitaContrasena2.setForeground(new java.awt.Color(255, 255, 255));
        cajitaContrasena2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajitaContrasena2.setBorder(null);
        cajitaContrasena2.setEchoChar('\u25cf');
        panelPopap.add(cajitaContrasena2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 570, 40));
        cajitaContrasena2.getAccessibleContext().setAccessibleName("");

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        panelPopap.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 570, 10));
        jSeparator4.getAccessibleContext().setAccessibleName("");

        panelAdd.setBackground(new java.awt.Color(255, 102, 255));
        panelAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelAddMouseExited(evt);
            }
        });

        txtAgregarContraseña.setBackground(new java.awt.Color(255, 102, 255));
        txtAgregarContraseña.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtAgregarContraseña.setForeground(new java.awt.Color(255, 255, 255));
        txtAgregarContraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAgregarContraseña.setText("Agregar Contraseña");
        txtAgregarContraseña.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 0), new java.awt.Color(153, 153, 255)));

        javax.swing.GroupLayout panelAddLayout = new javax.swing.GroupLayout(panelAdd);
        panelAdd.setLayout(panelAddLayout);
        panelAddLayout.setHorizontalGroup(
            panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtAgregarContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelAddLayout.setVerticalGroup(
            panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtAgregarContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        panelPopap.add(panelAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, 140, 30));

        interfazAgregarContraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        interfazAgregarContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/imagenes/interfazAddPasswordl.png"))); // NOI18N
        interfazAgregarContraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(172, 138, 24)));
        interfazAgregarContraseña.setMaximumSize(new java.awt.Dimension(870, 580));
        interfazAgregarContraseña.setMinimumSize(new java.awt.Dimension(870, 580));
        interfazAgregarContraseña.setPreferredSize(new java.awt.Dimension(870, 580));
        panelPopap.add(interfazAgregarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelPopap, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelPopap, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelPrincipal.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cargarNombres() {
        int indice = 0;
        String cadena = " ";

        List<ContrasenasGuardadas> miArregloContrasenas;
        String correo = recibirCorreo.getText();
        String contrasenna = recibirContrasena.getText();
        ContrasenasGuardadasDAO miDaoContrasenas = new ContrasenasGuardadasDAO();
        miModeloNombre.addElement(cadena);
        codigoNombre.put(0, 0);

        miArregloContrasenas = miDaoContrasenas.listadito("", correo, contrasenna);

        for (ContrasenasGuardadas objeto : miArregloContrasenas) {
            indice++;
            miModeloNombre.addElement(objeto.getNombrePagina());
            codigoNombre.put(indice, objeto.getCodContraGuard());

        }

        comboBuscador.setModel(miModeloNombre);

    }

    private void cargarNombresEspecificos(String buscador, int index) {

        int indice = 0;
        String cadena = "  ";
        List<ContrasenasGuardadas> miArregloContrasenas;
        ContrasenasGuardadas objetito = new ContrasenasGuardadas();

        String correo = recibirCorreo.getText();
        String contrasenna = recibirContrasena.getText();

        String[] nombreSeleccionado = new String[10];
        String[] cadenitaUrl = new String[10];
        String[] cadenitaaNombre = new String[10];
        String[] cadenaContrasenna = new String[10];
        ContrasenasGuardadasDAO miDaoContrasenas = new ContrasenasGuardadasDAO();

        miModeloNombre.addElement(cadena);
        codigoNombre.put(0, 0);

        miArregloContrasenas = miDaoContrasenas.listadito2("", buscador, correo, contrasenna);
        for (ContrasenasGuardadas objeto : miArregloContrasenas) {
            indice++;
            miModeloNombre.addElement(objeto.getNombrePagina());
            codigoNombre.put(indice, objeto.getCodContraGuard());
            nombreSeleccionado[indice] = objeto.getNombrePagina();
            cadenitaUrl[indice] = objeto.getUrl();
            cadenitaaNombre[indice] = objeto.getNombreUsuario();
            cadenaContrasenna[indice] = objeto.getContrasenasGuardadas();

        }
        if (miModeloNombre.getSize() == 1) {
            miModeloNombre.removeAllElements();
            cargarNombres();
            lblname.setText("No existe ninguna contraseña");
            cajitaURL.setText("");
            cajitaNombredeUsuario.setText("");
            cajitaContrasena.setText("");
        } else {

            comboBuscador.setModel(miModeloNombre);
            lblname.setText(nombreSeleccionado[1]);
            cajitaURL.setText(cadenitaUrl[1]);
            cajitaNombredeUsuario.setText(cadenitaaNombre[1]);
            cajitaContrasena.setText(cadenaContrasenna[1]);
            lblUrl.setText(cadenitaUrl[1]);
            lblNombreUsu.setText(cadenitaaNombre[1]);
            lblContrasenna.setText(cadenaContrasenna[1]);

            miModeloNombre.removeAllElements();
            cargarNombres();
        }
    }

    public void transparente() {
        cajitaContrasena.setBackground(new Color(45, 183, 205, 76));
        cajitaNombreWeb2.setBackground(new Color(45, 183, 205, 76));
        cajitaContrasena2.setBackground(new Color(45, 183, 205, 76));
        cajitaNombreUsuario2.setBackground(new Color(45, 183, 205, 76));
        cajitaURL2.setBackground(new Color(45, 183, 205, 76));
        cajitaNombredeUsuario.setBackground(new Color(45, 183, 205, 76));
        cajitaURL.setBackground(new Color(45, 183, 205, 76));

        buscadorTxt.setBackground(new Color(0, 0, 0, 0));
        panelDevolver.setBackground(new Color(0, 0, 0, 0));
        iconDevolver2.setVisible(false);
        iconDevolver3.setVisible(false);
        ojoNoOculto.setVisible(false);

        CopiarC.setBackground(new Color(0, 0, 0, 0));
        copiarUrl.setBackground(new Color(0, 0, 0, 0));
        copiarU.setBackground(new Color(0, 0, 0, 0));

        txtCopy1.setVisible(false);
        txtCopy2.setVisible(false);
        txtCopy3.setVisible(false);

    }


    private void panelAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAgregarMouseClicked

        panelPrincipal.setVisible(false);
        panelPopap.setVisible(true);
        lblActualizacion.setText("");
    }//GEN-LAST:event_panelAgregarMouseClicked

    private void panelAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAddMouseExited
        panelAdd.setBackground(new Color(255, 102, 255));
    }//GEN-LAST:event_panelAddMouseExited

    private void panelAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAddMouseEntered
        panelAdd.setBackground(new Color(212, 51, 181));

    }//GEN-LAST:event_panelAddMouseEntered

    private void panelBuscadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBuscadorMouseEntered
        panelBuscador.setBackground(new Color(226, 177, 29));
    }//GEN-LAST:event_panelBuscadorMouseEntered

    private void panelBuscadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBuscadorMouseExited
        panelBuscador.setBackground(new Color(255, 204, 51));
    }//GEN-LAST:event_panelBuscadorMouseExited

    private void panelAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAgregarMouseEntered
        panelAgregar.setBackground(new Color(212, 51, 181));
    }//GEN-LAST:event_panelAgregarMouseEntered

    private void panelAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAgregarMouseExited
        panelAgregar.setBackground(new Color(255, 102, 255));
    }//GEN-LAST:event_panelAgregarMouseExited

    private void panelActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelActualizarMouseEntered
        panelActualizar.setBackground(new Color(84, 171, 214));
    }//GEN-LAST:event_panelActualizarMouseEntered

    private void panelActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelActualizarMouseExited
        panelActualizar.setBackground(new Color(102, 204, 255));

    }//GEN-LAST:event_panelActualizarMouseExited

    private void panelBorrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBorrarMouseExited
        panelBorrar.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_panelBorrarMouseExited

    private void panelBorrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBorrarMouseEntered

        panelBorrar.setBackground(new Color(210, 106, 106));
    }//GEN-LAST:event_panelBorrarMouseEntered

    private void panelMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_panelMinimizarMouseClicked

    private void panelMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMinimizarMouseEntered
        iconMinimizar.setVisible(false);
        iconMinimizar2.setVisible(true);
        panelMinimizar.setBackground(new Color(137, 110, 21));
    }//GEN-LAST:event_panelMinimizarMouseEntered

    private void panelMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMinimizarMouseExited

        iconMinimizar.setVisible(true);
        iconMinimizar2.setVisible(false);
        panelMinimizar.setBackground(new Color(172, 138, 24));

    }//GEN-LAST:event_panelMinimizarMouseExited

    private void panelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCerrarMouseClicked
        int opcion;
        String opcionesBotones[] = {"Salir", "Cancelar"};
        opcion = JOptionPane.showOptionDialog(panelPrincipal, "¿Esta seguro que desea cerrar la sesion?",
                "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
                null, opcionesBotones, opcionesBotones[0]);
        if (opcion == JOptionPane.YES_NO_OPTION) {
            Login login = new Login();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_panelCerrarMouseClicked

    private void panelCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCerrarMouseEntered

        iconCerrar2.setVisible(false);
        iconCerrar.setVisible(true);
        panelCerrar.setBackground(new Color(226, 66, 66));
    }//GEN-LAST:event_panelCerrarMouseEntered

    private void panelCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCerrarMouseExited

        iconCerrar.setVisible(false);
        iconCerrar2.setVisible(true);
        panelCerrar.setBackground(new Color(172, 138, 24));
    }//GEN-LAST:event_panelCerrarMouseExited

    private void panelMinimizar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMinimizar2MouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_panelMinimizar2MouseClicked

    private void panelMinimizar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMinimizar2MouseEntered
        lblMinimizar2.setVisible(false);
        lblMinimizar2_2.setVisible(true);
        panelMinimizar2.setBackground(new Color(137, 110, 21));
    }//GEN-LAST:event_panelMinimizar2MouseEntered

    private void panelMinimizar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMinimizar2MouseExited

        lblMinimizar2.setVisible(true);
        lblMinimizar2_2.setVisible(false);
        panelMinimizar2.setBackground(new Color(172, 138, 24));
    }//GEN-LAST:event_panelMinimizar2MouseExited

    private void panelDevolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDevolverMouseClicked

        int opcion;
        String opcionesBotones[] = {"Si", "Cancelar"};
        opcion = JOptionPane.showOptionDialog(panelPopap, "¿Esta seguro que desea ir atras?",
                "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE,
                null, opcionesBotones, opcionesBotones[0]);
        if (opcion == JOptionPane.YES_NO_OPTION) {

            panelPrincipal.setVisible(true);
            miModeloNombre.removeAllElements();
            PanelLogin.requestFocus();
            panelPopap.setVisible(false);
            borrar();

        }

    }//GEN-LAST:event_panelDevolverMouseClicked

    private void panelDevolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDevolverMouseExited

        iconDevolver.setVisible(true);
        iconDevolver2.setVisible(false);
        iconDevolver3.setVisible(false);

    }//GEN-LAST:event_panelDevolverMouseExited

    private void panelDevolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDevolverMouseEntered

        iconDevolver.setVisible(false);
        iconDevolver2.setVisible(true);
        iconDevolver3.setVisible(true);

    }//GEN-LAST:event_panelDevolverMouseEntered

    public void buscador() {

        String buscador2 = (String) comboBuscador.getSelectedItem();
        String buscador = buscadorTxt.getText();
        boolean buscador1 = buscadorTxt.getText().isEmpty();
        Integer item = comboBuscador.getSelectedIndex();

        if (buscador1 != true) {

            comboBuscador.removeAllItems();
            cargarNombresEspecificos(buscador, item);
        }
        if (miModeloNombre.getSize() < 1) {
            comboBuscador.removeAllItems();
            cargarNombres();
        } else {
            comboBuscador.removeAllItems();
            cargarNombres();
        }

        if (buscador1) {

            if (item > 0) {
                comboBuscador.removeAllItems();
                cargarNombresEspecificos(buscador2, item);
            } else {
                comboBuscador.removeAllItems();
                cargarNombres();
            }

        }

        if (miModeloNombre.getSize() == 1) {
            miModeloNombre.removeAllElements();
            cargarNombres();

        }

    }

    private void panelBuscadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBuscadorMouseClicked
        buscador();
    }//GEN-LAST:event_panelBuscadorMouseClicked

    private void comboBuscadorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBuscadorItemStateChanged
        buscadorTxt.setText("");
        panelBuscador.requestFocus();
    }//GEN-LAST:event_comboBuscadorItemStateChanged

    private void buscadorTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscadorTxtMouseClicked

        comboBuscador.setSelectedIndex(0);
        buscadorTxt.requestFocus();
        lblActualizacion.setText("");
    }//GEN-LAST:event_buscadorTxtMouseClicked

    private void panelCabeceraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCabeceraMousePressed
        posicionX = evt.getX();
        posicionY = evt.getY();
    }//GEN-LAST:event_panelCabeceraMousePressed

    private void panelCabeceraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCabeceraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - posicionX, y - posicionY);
    }//GEN-LAST:event_panelCabeceraMouseDragged

    private void buscadorTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_buscadorTxtFocusGained
        if (comboBuscador.getSelectedIndex() != 0) {
            panelBuscador.requestFocus();
        }
    }//GEN-LAST:event_buscadorTxtFocusGained

    private void panelCabecera2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCabecera2MousePressed
        posicionX = evt.getX();
        posicionY = evt.getY();
    }//GEN-LAST:event_panelCabecera2MousePressed

    private void panelCabecera2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCabecera2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - posicionX, y - posicionY);
    }//GEN-LAST:event_panelCabecera2MouseDragged

    private void verContrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verContrasenaMouseClicked
        count++;
        if (count % 2 == 0) {
            ojoOculto.setVisible(true);
            ojoNoOculto.setVisible(false);
            cajitaContrasena2.setEchoChar('\u25cf');
        } else {
            ojoOculto.setVisible(false);
            ojoNoOculto.setVisible(true);
            cajitaContrasena2.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_verContrasenaMouseClicked

    private void panelAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAddMouseClicked
        AceptarPanelAdd();


    }//GEN-LAST:event_panelAddMouseClicked

    private void PanelLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PanelLoginFocusGained
        cargarNombres();
    }//GEN-LAST:event_PanelLoginFocusGained

    private void comboBuscadorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboBuscadorFocusLost

        String buscador = (String) comboBuscador.getSelectedItem();
        Integer item = comboBuscador.getSelectedIndex();
        if (item != 0) {
            comboBuscador.removeAllItems();
            cargarNombresEspecificos(buscador, item);

        }
    }//GEN-LAST:event_comboBuscadorFocusLost

    private void verContrasena1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verContrasena1MouseClicked
        count2++;
        if (count2 % 2 == 0) {
            ojoOculto1.setVisible(true);
            ojoNoOculto1.setVisible(false);
            miremos.setVisible(true);
        } else {
            ojoOculto1.setVisible(false);
            ojoNoOculto1.setVisible(true);
            miremos.setVisible(false);
        }
    }//GEN-LAST:event_verContrasena1MouseClicked

    private void borrar() {
        lblname.setText("Seleccione una contraseña -->");
        cajitaURL.setText("");
        cajitaContrasena.setText("");
        cajitaNombredeUsuario.setText("");
        cajitaContrasena2.setText("");
        cajitaNombreUsuario2.setText("");
        cajitaNombreWeb2.setText("");
        cajitaURL2.setText("");

    }

    private void actualizado() {

        String url = cajitaURL.getText();
        String nombreUsu = cajitaNombredeUsuario.getText();
        String contrasena = cajitaContrasena.getText();

        String nombrePagina = lblname.getText();
        String urlComparar = lblUrl.getText();
        String nombreUsuComparar = lblNombreUsu.getText();
        String contrasennaComparar = lblContrasenna.getText();

        String contrasennaOculta = recibirContrasena.getText();
        String correoOculto = recibirCorreo.getText();

        Acceso objAcceso = new Acceso(null, correoOculto, contrasennaOculta);

        ContrasenasGuardadasDAO miDaoContraGuard = new ContrasenasGuardadasDAO();

        ContrasenasGuardadas objContrasenasGuardadas = new ContrasenasGuardadas(0, objAcceso, nombrePagina, url, nombreUsu, contrasena);
        ContrasenasGuardadas objContrasenasGuardadas2 = new ContrasenasGuardadas(0, null, null, urlComparar, nombreUsuComparar, contrasennaComparar);

        if (miDaoContraGuard.actualizar(objContrasenasGuardadas, objContrasenasGuardadas2)) {
            miModeloNombre.removeAllElements();
            cargarNombres();
            lblActualizacion.setText("Actualización de datos completa");

            lblTitulo.requestFocus();

        } else {
            lblActualizacion.setText("Actualización interrumpida, intentalo nuevamente");
        }

    }

    private void borrado() {
        actualizado();
        String url = cajitaURL.getText();
        String nombreUsu = cajitaNombredeUsuario.getText();
        String contrasena = cajitaContrasena.getText();
        String nombrePagina = lblname.getText();

        String contrasennaOculta = recibirContrasena.getText();
        String correoOculto = recibirCorreo.getText();

        Acceso objAcceso = new Acceso(null, correoOculto, contrasennaOculta);

        ContrasenasGuardadasDAO miDaoContraGuard = new ContrasenasGuardadasDAO();

        ContrasenasGuardadas objContrasenasGuardadas = new ContrasenasGuardadas(0, objAcceso, nombrePagina, url, nombreUsu, contrasena);

        if (miDaoContraGuard.borrar(objContrasenasGuardadas)) {
            miModeloNombre.removeAllElements();
            cargarNombres();
            lblActualizacion.setText("Eliminación del dato completada");
            borrar();
        } else {
            lblActualizacion.setText("Eliminación interrumpida, intentelo nuevamente");
        }
    }

    private void panelActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelActualizarMouseClicked
        actualizado();
        borrar();
    }//GEN-LAST:event_panelActualizarMouseClicked

    private void panelBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBorrarMouseClicked

        borrado();
    }//GEN-LAST:event_panelBorrarMouseClicked

    private void comboBuscadorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboBuscadorFocusGained
        lblActualizacion.setText("");
    }//GEN-LAST:event_comboBuscadorFocusGained

    private void lblAgregarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblAgregarFocusLost
        lblAgregar.setText("");
    }//GEN-LAST:event_lblAgregarFocusLost

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_formFocusLost

    private void copiarUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiarUrlActionPerformed
        cajitaURL.selectAll();
        cajitaURL.copy();
        txtCopy1.setVisible(true);
        copiarUrl.requestFocus();
    }//GEN-LAST:event_copiarUrlActionPerformed

    private void copiarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiarUActionPerformed
        cajitaNombredeUsuario.selectAll();
        cajitaNombredeUsuario.copy();
        txtCopy2.setVisible(true);
        copiarU.requestFocus();
    }//GEN-LAST:event_copiarUActionPerformed

    private void CopiarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CopiarCActionPerformed
        cajitaContrasena.selectAll();
        cajitaContrasena.copy();
        txtCopy3.setVisible(true);
        CopiarC.requestFocus();

    }//GEN-LAST:event_CopiarCActionPerformed

    private void copiarUrlFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_copiarUrlFocusLost
        txtCopy1.setVisible(false);
    }//GEN-LAST:event_copiarUrlFocusLost

    private void copiarUFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_copiarUFocusLost
         txtCopy2.setVisible(false);
    }//GEN-LAST:event_copiarUFocusLost

    private void CopiarCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CopiarCFocusLost
        txtCopy3.setVisible(false);
    }//GEN-LAST:event_CopiarCFocusLost
    private void AceptarPanelAdd() {

        String nombreWebTexto, urlTexto, nombreUsuarioTexto, contrasennaTexto, correoCifrado, claveCifrada;
        correoCifrado = recibirCorreo.getText();
        claveCifrada = recibirContrasena.getText();
        nombreWebTexto = cajitaNombreWeb2.getText();
        urlTexto = cajitaURL2.getText();
        nombreUsuarioTexto = cajitaNombreUsuario2.getText();
        contrasennaTexto = String.valueOf(cajitaContrasena2.getPassword());

        if (nombreWebTexto.isEmpty() || urlTexto.isEmpty() || nombreUsuarioTexto.isEmpty() || contrasennaTexto.isEmpty()) {
            JOptionPane.showMessageDialog(panelPopap, "Completa todos los campos de información", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {

            ContrasenasGuardadasDAO objContraGuardDAO = new ContrasenasGuardadasDAO();

            Acceso objAcces = new Acceso(null, correoCifrado, claveCifrada);

            ContrasenasGuardadas objContraGuard = new ContrasenasGuardadas(0, objAcces, nombreWebTexto, urlTexto, nombreUsuarioTexto, contrasennaTexto);

            if (objContraGuardDAO.agregar(objContraGuard)) {
                borrar();
                lblAgregar.setText("Contraseña agregada correctamente");
                lblAgregar.requestFocus();

            } else {
                JOptionPane.showMessageDialog(panelPopap, "Vuelve a revisar los datos", "Advertencia", JOptionPane.WARNING_MESSAGE);

            }
        }
    }

    private void cambiarIcono() {
        String rutaImagenIcono = getClass().
                getResource(MisVariables.RUTA_IMAGENES + "/" + MisVariables.ICONO_PROYECTO).
                getPath();
        ImageIcon miIcono = new ImageIcon(rutaImagenIcono);
        this.setIconImage(miIcono.getImage());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Principal().setVisible(true);
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CopiarC;
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JLabel btnActualizar;
    private javax.swing.JLabel btnAgregar;
    private javax.swing.JLabel btnBorrar;
    private javax.swing.JTextField buscadorTxt;
    private javax.swing.JTextField cajitaContrasena;
    private javax.swing.JPasswordField cajitaContrasena2;
    private javax.swing.JTextField cajitaNombreUsuario2;
    private javax.swing.JTextField cajitaNombreWeb2;
    private javax.swing.JTextField cajitaNombredeUsuario;
    private javax.swing.JTextField cajitaURL;
    private javax.swing.JTextField cajitaURL2;
    private javax.swing.JComboBox<String> comboBuscador;
    private javax.swing.JButton copiarU;
    private javax.swing.JButton copiarUrl;
    private javax.swing.JLabel iconBuscador;
    private javax.swing.JLabel iconCerrar;
    private javax.swing.JLabel iconCerrar2;
    private javax.swing.JLabel iconDevolver;
    private javax.swing.JLabel iconDevolver2;
    private javax.swing.JLabel iconDevolver3;
    private javax.swing.JLabel iconLogin;
    private javax.swing.JLabel iconMinimizar;
    private javax.swing.JLabel iconMinimizar2;
    private javax.swing.JLabel interfazAgregarContraseña;
    private javax.swing.JLabel interfazPrincipal;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblActualizacion;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblBuscador;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblContrasenna;
    private javax.swing.JLabel lblLogo2;
    private javax.swing.JLabel lblMinimizar2;
    private javax.swing.JLabel lblMinimizar2_2;
    private javax.swing.JLabel lblNameUsu;
    private javax.swing.JLabel lblNombreUsu;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblNombreWeb;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblURL;
    private javax.swing.JLabel lblUrl;
    private javax.swing.JLabel lblUrl3;
    private javax.swing.JLabel lblcontra;
    private javax.swing.JLabel lblname;
    private javax.swing.JTextField miremos;
    private javax.swing.JLabel ojoNoOculto;
    private javax.swing.JLabel ojoNoOculto1;
    private javax.swing.JLabel ojoOculto;
    private javax.swing.JLabel ojoOculto1;
    private javax.swing.JPanel panelActualizar;
    private javax.swing.JPanel panelAdd;
    private javax.swing.JPanel panelAgregar;
    private javax.swing.JPanel panelBorrar;
    private javax.swing.JPanel panelBuscador;
    private javax.swing.JPanel panelCabecera;
    private javax.swing.JPanel panelCabecera2;
    private javax.swing.JPanel panelCerrar;
    private javax.swing.JPanel panelDevolver;
    private javax.swing.JPanel panelLogo2;
    private javax.swing.JPanel panelMinimizar;
    private javax.swing.JPanel panelMinimizar2;
    private javax.swing.JPanel panelPopap;
    private javax.swing.JPanel panelPrincipal;
    public static javax.swing.JTextField recibirContrasena;
    public static javax.swing.JTextField recibirCorreo;
    private javax.swing.JSeparator separadorContraseña;
    private javax.swing.JSeparator separadorNombreUsuario;
    private javax.swing.JSeparator separadorURL;
    private javax.swing.JLabel txtAgregarContraseña;
    private javax.swing.JLabel txtCopy1;
    private javax.swing.JLabel txtCopy2;
    private javax.swing.JLabel txtCopy3;
    private javax.swing.JPanel verContrasena;
    private javax.swing.JPanel verContrasena1;
    // End of variables declaration//GEN-END:variables
}
